---
title: "Table 1"
output: word_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
#loading libraries
library(gtsummary)
library(tidyverse)
BRFSS <- read.csv("/Users/mirtamaravilla/Documents/UW Courses/Spring Qtr 2024/EPI 514 /EPI 514 Research/cleanbrfss.csv") 

```

```{r}
##TABLE 1

theme_gtsummary_journal(journal = "jama")
Setting theme `JAMA` theme_gtsummary_compact(font_size = 10)
Setting theme `Compact`
 
table1 <- BRFSS %>%
select("sex", "HlthDiscrim.f", "CervScrnEver.f", "CervScrnHPV.f", 
"CervScrnPAP.f", "HadHyst.f", "RaceOthers.f", "income.f", 
 "employ.f", "insurance.f", "edu.f", "age.f", "GenHlth.f") %>%

tbl_summary(by = "HlthDiscrim.f", 
 missing = "ifany", 
type = list(
 sex ~ "categorical", 
 CervScrnEver  ~ "categorical", 
                                    CervScrnHPV.f ~ "categorical", 
                                     CervScrnPAP.f ~ "categorical", 
                                     HadHyst.f ~ "categorical", 
                                     RaceOthers.f  ~ "categorical",
                                     income.f ~ "categorical",
                                    employ.f ~ "categorical",
                                     insurance.f ~ "categorical",
                                     edu.f ~ "categorical",
                                     age.f ~ "categorical", 
                                     GenHlth.f ~ "categorical"),
                                   statistic = all_continuous() ~ "{mean} ({sd})",
                                  digits = list(all_continuous() ~ 1,
                                  all_categorical() ~ c(0, 1)), 
                                   label = list(
                                       sex ~ "Sex", 
                                       CervScrnEver.f  ~ "Cervical Cancer Screening Test", 
                                       CervScrnHPV.f ~ "HPV Test", 
                                       CervScrnPAP.f ~ "Pap Test", 
                                       HadHyst.f ~ "Hyesterectomy", 
                                       RaceOthers.f  ~ "Race and Ethnicity",
                                       income.f ~ "Annual Household Income",
                                       employ.f ~ "Employed",
                                       insurance.f ~ "Health Coverage",
                                       edu.f ~ "Education Status",
                                       age.f~ "Age (years)", 
                                       GenHlth.f ~ "Health Status"
                                     )) %>%
                   add_overall() %>%
                   modify_header(label = "**Variable**") %>%
                   modify_spanning_header(list(stat_1 ~ "**Percieved Discrimination**",
                                               stat_2 ~ "**Percieved Discrimination**",
                                                stat_3 ~ "**Percieved Discrimination**"))

```



```{r }

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
